# Model Training

In this notebook, we will ask you a series of questions regarding model selection. Based on your responses, we will ask you to create the ML models that you've chosen. 

The bonus step is completely optional, but if you provide a sufficient third machine learning model in this project, we will add `1000` points to your Kahoot leaderboard score.

**Note**: Use the dataset that you've created in your previous data transformation step (not the original model).

## Questions
Is this a classification or regression task?  

Fraud detection in this dataset is a classification task.

Are you predicting for multiple classes or binary classes?  

It is a binary classification because it's predicting one of two classes.

Given these observations, which 2 (or possibly 3) machine learning models will you choose?  

List your models here

Logistic Regression is simple to use. It can scale and log transformation.
KNN is simple to understand and implement. It can be used for both classification and regression tasks.

## First Model

Using the first model that you've chosen, implement the following steps.

In [36]:
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split, RandomizedSearchCV, GridSearchCV

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import time

### 1) Create a train-test split

Use your cleaned and transformed dataset to divide your features and labels into training and testing sets. Make sure you’re only using numeric or properly encoded features.

In [37]:
transactions1 = pd.read_csv("../data/bank_transactions.csv")
sample_transactions1 = transactions1.sample(n=5000, random_state=42)

X = sample_transactions1.drop(columns=["isFraud"])
y = sample_transactions1["isFraud"]

# View first 5 rows of predictors
print(X.head())

            type     amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
987231   CASH_IN   54152.03   C865744496       42823.36        96975.39
79954    CASH_IN  279331.66  C1710599742     8385167.08      8664498.74
567130  CASH_OUT  185673.97  C1570683955           0.00            0.00
500891  CASH_OUT  128216.41   C150381134       12158.00            0.00
55399    PAYMENT   17567.71   C660181819      104890.00        87322.29

           nameDest  oldbalanceDest  newbalanceDest  isFlaggedFraud
987231   C667346055     11438021.32     10695480.59               0
79954   C1699377197       394276.66       114945.00               0
567130  C1562349196       396994.01       582667.97               0
500891  C1245613416     17406313.64     17534530.05               0
55399   M1631019047            0.00            0.00               0

In [38]:
# view first 5 rows of predictors
X.head()

,type,amount,nameOrig,oldbalanceOrg,newbalanceOrig,nameDest,oldbalanceDest,newbalanceDest,isFlaggedFraud
987231,CASH_IN,54152.03,C865744496,42823.36,96975.39,C667346055,11438021.32,10695480.59,0
79954,CASH_IN,279331.66,C1710599742,8385167.08,8664498.74,C1699377197,394276.66,114945.00,0
567130,CASH_OUT,185673.97,C1570683955,0.00,0.00,C1562349196,396994.01,582667.97,0
500891,CASH_OUT,128216.41,C150381134,12158.00,0.00,C1245613416,17406313.64,17534530.05,0
55399,PAYMENT,17567.71,C660181819,104890.00,87322.29,M1631019047,0.00,0.00,0

In [39]:
# view first 5 random samples of target data
y.sample(5)

446355    0
268993    0
104235    0
683061    0
971065    0
Name: isFraud, dtype: int64

In [40]:
# TODO: select predictors for your predictors
X = X[['oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest']]

# TODO: split into test and training sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# view first 5 rows of training data
X_train.head()

        oldbalanceOrg  newbalanceOrig  oldbalanceDest
240187            0.0            0.00       765886.91
850660            0.0            0.00       797034.72
182322         5312.0        64993.01       885612.00
931658            0.0            0.00            0.00
471883        22298.0            0.00            0.00

### 2) Search for best hyperparameters
Use tools like GridSearchCV, RandomizedSearchCV, or model-specific tuning functions to find the best hyperparameters for your first model.

In [41]:
# Randomly search for the best hyperparameters on a logistic regression model
param_dist = {
    'penalty': ['l1', 'l2'],
    'C': np.linspace(0.01, 1, 100),
    'solver': ['saga'],
    'max_iter': [10000]
}

random_search = RandomizedSearchCV(LogisticRegression(), param_distributions=param_dist, cv=5, scoring='accuracy', random_state=42)
random_search.fit(X_train, y_train)


# Best model from random search
best_params_random = random_search.best_params_
best_score_random = random_search.best_score_


print(f"RandomizedSearchCV - Best Params: {best_params_random}")
print(f"RandomizedSearchCV - Cross-Val Accuracy: {best_score_random:.2f}")

c:\Users\Owner\miniconda3\envs\ds\Lib\site-packages\sklearn\model_selection\_split.py:805: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(

RandomizedSearchCV - Best Params: {'solver': 'saga', 'penalty': 'l2', 'max_iter': 10000, 'C': np.float64(0.48000000000000004)}
RandomizedSearchCV - Cross-Val Accuracy: 1.00

### 3) Train your model
Select the model with best hyperparameters and generate predictions on your test set. Evaluate your models accuracy, precision, recall, and sensitivity.

In [13]:
# Randomly search for the best hyperparameters on a logistic regression model
param_dist = {
    'penalty': ['l1', 'l2'],
    'C': np.linspace(0.01, 1, 100),
    'solver': ['saga'],
    'max_iter': [10000]
}


random_search = RandomizedSearchCV(LogisticRegression(), param_distributions=param_dist, cv=5, scoring='accuracy', random_state=42)
random_search.fit(X_train, y_train)


# Best model from random search
best_params_random = random_search.best_params_
best_score_random = random_search.best_score_


print(f"RandomizedSearchCV - Best Params: {best_params_random}")
print(f"RandomizedSearchCV - Cross-Val Accuracy: {best_score_random:.2f}")

c:\Users\Owner\miniconda3\envs\ds\Lib\site-packages\sklearn\model_selection\_split.py:805: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(

RandomizedSearchCV - Best Params: {'solver': 'saga', 'penalty': 'l2', 'max_iter': 10000, 'C': np.float64(0.48000000000000004)}
RandomizedSearchCV - Cross-Val Accuracy: 1.00

## Second Model

Create a second machine learning object and rerun steps (2) & (3) on this model. Compare accuracy metrics between these two models. Which handles the class imbalance more effectively?

In [14]:
#KNN Model
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score

# Load data
transactions1 = pd.read_csv("../data/bank_transactions.csv")

sample_transactions = transactions1.sample(n=1000, random_state=42)

# Set your target column name (replace this with the actual name)
target_column = "isFraud" 

# Separate features and target
X = sample_transactions.drop(columns=["isFraud"])
y = sample_transactions["isFraud"]

# Convert categorical columns to numeric using one-hot encoding
X_encoded = pd.get_dummies(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

# Scale features (KNN needs this)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train KNN
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_scaled, y_train)

# Predict and evaluate
y_pred = knn.predict(X_test_scaled)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.995
Classification Report:
               precision    recall  f1-score   support

           0       0.99      1.00      1.00       199
           1       0.00      0.00      0.00         1

    accuracy                           0.99       200
   macro avg       0.50      0.50      0.50       200
weighted avg       0.99      0.99      0.99       200

c:\Users\Owner\miniconda3\envs\ds\Lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "c:\Users\Owner\miniconda3\envs\ds\Lib\site-packages\joblib\externals\loky\backend\context.py", line 257, in _count_physical_cores
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "c:\Users\Owner\miniconda3\envs\ds\Lib\subprocess.py", line 550, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Owner\miniconda3\envs\ds\Lib\subprocess.py", line 1028, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\Owner\miniconda3\envs\ds\Lib\subprocess.py", line 1540, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
c:\Users\Owner\miniconda3\envs\ds\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Owner\miniconda3\envs\ds\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\Owner\miniconda3\envs\ds\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

## Q3

After exploring your data, you may have noticed that fraudulent transactions are rare compared to non-fraudulent ones. What challenges might this pose when training a machine learning model? What strategies could you use to ensure your model learns meaningful patterns from the minority class? Apply your data transformations (if any) in the code-block below.

We can see that percent of Non-Fraud (0) is 99.87% while Fraud (1) is 0.13%. The dataset is highly imbalanced, a simple model could achieve 99.87% accuracy just by always predicting "non-fraud." However, this would completely fail to detect any real fraud cases, resulting in a Recall of 0 for the minority class. One way to fix this is to use SMOTE to oversample the minority class within each fold of cross-validation this ensures the resampling respects the original class distribution by stratifying during the split. It will help the model to learn meaningful patterns from the rare fraud cases during training.

In [15]:
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE

In [ ]:
#transactions1 = pd.read_csv("../data/bank_transactions.csv")
#sample_transactions2 = transactions1.sample(n=6000, random_state=42)

#X = sample_transactions2.drop(columns=["isFraud"])
#y = sample_transactions2["isFraud"]

# View first 5 rows of predictors
#print(X1.head())

            type     amount     nameOrig  oldbalanceOrg  newbalanceOrig  \
987231   CASH_IN   54152.03   C865744496       42823.36        96975.39
79954    CASH_IN  279331.66  C1710599742     8385167.08      8664498.74
567130  CASH_OUT  185673.97  C1570683955           0.00            0.00
500891  CASH_OUT  128216.41   C150381134       12158.00            0.00
55399    PAYMENT   17567.71   C660181819      104890.00        87322.29

           nameDest  oldbalanceDest  newbalanceDest  isFlaggedFraud
987231   C667346055     11438021.32     10695480.59               0
79954   C1699377197       394276.66       114945.00               0
567130  C1562349196       396994.01       582667.97               0
500891  C1245613416     17406313.64     17534530.05               0
55399   M1631019047            0.00            0.00               0

In [49]:
#X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=42)

In [46]:
smote = SMOTE(random_state=42,k_neighbors=2)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [47]:
print(sample_transactions['isFraud'].value_counts())

isFraud
0    999
1      1
Name: count, dtype: int64

In [48]:
y_train_resampled.value_counts()

isFraud
0    3997
1    3997
Name: count, dtype: int64

### (Bonus/Optional) Third Model

Create a third machine learning model and rerun steps (2) & (3) on this model. Which model has the best predictive capabilities? 

Create as many code-blocks as needed.